### ISSUE TITLE
Название файла на русском языке

### ISSUE THREAD

**Issue by MsSparrow** [iplus/voice-actor-word-calculator#1]
Код не работает, если называние файла полностью или частично написано на русском языке

**Comment by iplus** [comment]
не могу воспроизвести, нужно описание в каком браузере не работает и пример файла, проблема может быть не в названии, а в содержимом

**Comment by MsSparrow** [comment]
Google Chrome Версия 104.0.5112.81 (Официальная сборка), (64 бит)
Вот этот файл для примера

[Любовь напоказ 1.46.docx](https://github.com/iplus/voice-actor-word-calculator/files/9354242/1.46.docx)
)

**Comment by iplus** [comment]
думаю проблема была в начинке, сейчас любая таблица из файла считается содержащей реплики (три колонки ожидаются, время, актер, текст). в этом файле было две таблицы, из-за первой таблицы умирал парсер. 

текущая версия сайта будет отображать этот файл вот так:

![image](https://user-images.githubusercontent.com/2189037/184975951-1ed17a99-955a-4581-adf6-0e6cd75139e2.png)
